# setwd("~/Desktop/Analysis/data")
rawDataPath<- file.path( 'dataRaw/dataE1' ) #Cheryl-prepared files

Session1 <-read.table(  file.path(rawDataPath, "23-1_01Jun2017_14-03.txt")    ,sep="\t", header=TRUE)
Session2 <-read.table(   file.path(rawDataPath,"23-2_01Jun2017_14-21.txt")    ,sep="\t", header=TRUE)
Session2$trialnum <- Session2$trialnum+100
 DataSet <-rbind(Session1,Session2)
 
 #response0 position in the stream
 DataSet$cueResponsePos0 <- DataSet$cueSerialPos0 + DataSet$responsePosRelative0
 #response1 position in the stream
 DataSet$cueResponsePos1 <- DataSet$cueSerialPos1 + DataSet$responsePosRelative1
 
 DataSet$wordEcc <- as.numeric(DataSet$wordEcc)
 DataSet$noisePercent <- as.numeric(DataSet$noisePercent)
 DataSet <- DataSet[,c(-20,-21)]
 answerleft <-apply(DataSet,1,function(x) if (x['rightResponseFirst']=="False ") x['answer0'] else x['answer1'])
 responseleft <-apply(DataSet,1,function(x) if (x['rightResponseFirst']=="False ") x['response0'] else x['response1'])
 correctleft <-apply(DataSet,1,function(x) if (x['rightResponseFirst']=="False ") x['correct0'] else x['correct1'])
 cueSerialPosleft <-apply(DataSet,1,function(x) if (x['rightResponseFirst']=="False ") x['cueSerialPos0'] else x['cueSerialPos1'])
 responsePosRelativeleft <-apply(DataSet,1,function(x) if (x['rightResponseFirst']=="False ") x['responsePosRelative0'] else x['responsePosRelative1'])
 
 answerright <-apply(DataSet,1,function(x) if (x['rightResponseFirst']=="True ") x['answer0'] else x['answer1'])
 responseright <-apply(DataSet,1,function(x) if (x['rightResponseFirst']=="True ") x['response0'] else x['response1'])
 correctright <-apply(DataSet,1,function(x) if (x['rightResponseFirst']=="True ") x['correct0'] else x['correct1'])
 cueSerialPosright <-apply(DataSet,1,function(x) if (x['rightResponseFirst']=="True ") x['cueSerialPos0'] else x['cueSerialPos1'])
 responsePosRelativeright <-apply(DataSet,1,function(x) if (x['rightResponseFirst']=="True ") x['responsePosRelative0'] else x['responsePosRelative1'])
 
 DataSet <- cbind(DataSet,answerleft, correctleft, cueSerialPosleft, responseleft, responsePosRelativeleft, answerright, correctright,cueSerialPosright,responseright,responsePosRelativeright)

 near <- DataSet[DataSet$wordEcc==1,]
 far <- DataSet[DataSet$wordEcc==6,]
 leftfirst <- DataSet[DataSet$rightResponseFirst=="False ",]
 rightfirst <- DataSet[DataSet$rightResponseFirst=="True ",] 
 
 write.table(near, file="../Near-Far/Near-23.txt",row.names=FALSE,append=FALSE,sep="\t")
 write.table(far,file = "../Near-Far/Far-23.txt",row.names=FALSE,append=FALSE,sep="\t")
 write.table(leftfirst,file = "../Left-Right/LeftFirst-23.txt",row.names=FALSE,append=FALSE,sep="\t")
 write.table(rightfirst,file = "../Left-Right/RightFirst-23.txt",row.names=FALSE,append=FALSE,sep="\t")
 write.table(DataSet, file="../CompiledData/DataSet-23.txt",row.names=FALSE,append=FALSE,sep="\t")

 
 # 1. in the initial text file generated by psychopy, columns, such as answer0, answer1, records the response according to the sequence of responses (i.e., when rightResponseFirst is true, answer0 means the answer for the right stream) not the position of responses, 
 #we tried to convert that back.  
 # 2. I compiled 5 files for each participants manually for my first experiment since it seemed to be an easier way to do. 
 # 3. I ran two sessions, with 100 trials each, for each participant in my first experiment. However, there was only one 200-trial session for each participant in the second experiment. 
 # 4. Participant 09 seemed not taking the experiment seriously, since she finished it really quickly and showed poor approximately correct rate for both streams. 
 
 